name: 'my_dbt_project'
version: '1.0.1'
config-version: 2

profile: 'crypto_data_pipeline'

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  my_dbt_project:
    crypto_data:
      +materialized: table
    metadata:
      +materialized: table
    distinct_symbols:
      +materialized: table
    timestamps:
      +materialized: table
    purchases:
      +materialized: table
