# put your configuration values here

[runtime]
log_level = "WARNING"  # the system log level of dlt
# use the dlthub_telemetry setting to enable/disable anonymous usage data reporting, see https://dlthub.com/docs/telemetry
dlthub_telemetry = true

[sources.crypto_data]
base_url = "https://data.alpaca.markets"
endpoint = "/v1beta3/crypto/us/bars"
start_date = "2022-01-01T00:00:00+00:00"
end_date = "2024-07-10T00:00:00+00:00"
timeframe = "1Day"
symbols = "BTC/USD"
